### ISSUE TITLE
Custom palette color namespacing.

### ISSUE THREAD

**Issue by notlee** [Financial-Times/o-colors#150]
It's possible to add a custom palette colour in a component using `oColorsSetColor`. This could then be used by a dependent client or component, without the dependent knowing it's not an official palette colour. This means components are unable to remove custom colours without potentially causing a visually breaking change.

Should we document within `o-colors`: unoffical palette colours _should_ be namespaced? And build in a mechanism to deprecate palette colors.

e.g.
https://github.com/Financial-Times/o-buttons/compare/mono-primary?expand=1
```
@include oColorsSetColor('slate-white-80', oColorsMix($color: 'slate', $background: 'white', $percentage: 80));
```
becomes
```
@include oColorsSetColor('o-buttons-slate-white-80', oColorsMix($color: 'slate', $background: 'white', $percentage: 80));
```

**Comment by gvonkoss** [comment]
I don't see much of an issue with that documentation. 

Could it be a semantic problem, however? 
Seeing as many of these new colours are coming into play because we are moving into the internal universe, perhaps they are colours that will be used throughout more than each individual component—it could be odd to use a variable called `o-buttons-black-white-10` for something that isn't a button, which could happen if that colour is available?

Would it be plausible to add to the `oColorsSetColor` mixin, and indicate what component has set this colour in some kind of warning?

**Comment by notlee** [comment]
Adding the component could be a good idea. We'd be able to warn and transition it seamlessly to the official palette. 

1. The warning would appear upon getting the colour, which I _think_ happens in `oColorsGetPaletteColor`, and would appear for the component which set the custom usecase which might be a bit annoying -- but fine?
2. We'd also need to enforce that a component name is given, so we'd need to deprecate `oColorsSetColor` in favour of something like `oColorsSetCustomColor($name, $color, $component, $is-deprecated: false)`

**Comment by notlee** [comment]
It's currently possible to override a color. Is there a problem with preventing that? It doesn't necessarily make sense to reassign a color.

**Comment by notlee** [comment]
Custom palette colour namespacing was already documented as a must. Sometimes this wasn't the case and made tracking down a missing colour difficult if it wasn't deprecated correctly. We decided to make the requirement explicit. See https://github.com/Financial-Times/o-colors/issues/198
